# Generated by Django 3.2.25 on 2024-03-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.DateField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('pre_event_image', models.ImageField(upload_to='images')),
                ('mid_event_image', models.ImageField(upload_to='images')),
                ('post_event_image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.assemblycategory')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.parliamentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('compliant', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.village')),
            ],
        ),
    ]
