# Generated by Django 3.2.25 on 2024-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20240330_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govtevent',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='govtevent',
            name='parliament',
        ),
        migrations.AddField(
            model_name='compliant',
            name='aadhar_no',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='AssemblyCategory',
        ),
        migrations.DeleteModel(
            name='GovtEvent',
        ),
        migrations.DeleteModel(
            name='ParliamentCategory',
        ),
    ]
